### ISSUE TITLE
Request to change nextflow-modules structure

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#102]
It's a hassle to have to push changes made to [nextflow-modules](https://github.com/genomic-medicine-sweden/nextflow-modules) and then push the same changes to this repository. I propose that nextflow-modules no longer be a submodule but instead have it offcially incorporated into JASEN.

**Comment by LordRust** [comment]
As long as we do not expect to have a common modules repo that will be re-used for various pipelines I think this makes more sense than the current design. If we some time in the future would like to have the common module repo it would be easy to change back. So, a yes from me.
