### ISSUE TITLE
Chewbbaca v3 is giving different results compared to v2

### ISSUE THREAD

**Issue by LordRust** [genomic-medicine-sweden/JASEN#104]
version 3 of chewbbaca changed the AlleleCall procedure. It seems like this results in more unassigned loci. Should be investigated if this is the correct way or not.

**Comment by ryanjameskennedy** [comment]
So basically we need to compare skesa vs spades outputs?

**Comment by LordRust** [comment]
That and the two versions of chewBBACA we have been using. Or if something else is off. It might just be the way it works in this version

**Comment by ryanjameskennedy** [comment]
This was solved by rerunning the `chewie PrepExternalSchema`
