### ISSUE TITLE
Output files symlinked instead of being copied

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#105]
The output files are symlinked to the nextflow `work/` directory which is created in the working directory. It needs to be copied instead using `publishDirMode = "copy"` as seen [here](https://github.com/genomic-medicine-sweden/JASEN/blob/56a0d898c95733f7c479e99529c9dd0e2c6a2062/configs/nextflow.base.config#L10), which doesn't seem to be working.

**Comment by LordRust** [comment]
We should also scale down significantly on what is published
