### ISSUE TITLE
E. coli wgMLST database

### ISSUE THREAD

**Issue by LordRust** [genomic-medicine-sweden/JASEN#120]
The database from chewbbaca.online has great potential for E. coli. Already formatted to chewBBACA

`curl --insecure -X GET "https://chewbbaca.online/NS/api/download/compressed_schemas/5/1/1" -H  "accept: application/json" > ec_chewie_online.zip`

Add this, either as default, or as an option

**Comment by ryanjameskennedy** [comment]
I have done this using the following command in `deploy_references_singularity.sh`:
```
singularity exec --bind $mntroot ${containerdir}/chewbbaca.sif chewie DownloadSchema -sp 5 -sc 1 -o ${assdir}/wgmlst/escherichia_coli/alleles --latest
```
