### ISSUE TITLE
GA stub-run self-test

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/jasen#153]

**Comment by ryanjameskennedy** [comment]
Nf-core raredisease has an [example of this](https://github.com/nf-core/raredisease/blob/master/.github/workflows/ci.yml). We may just have to add a `container = $container` line in the modules with the container paths provided by the config or (if config path not available) they're pulled automatically from [galaxy project](https://depot.galaxyproject.org/singularity/).

**Comment by ryanjameskennedy** [comment]
We need to try contributing to bioconda and hopefully that will produce a few of the containers that we need.

**Comment by mhkc** [comment]
That sounds like good idea

**Comment by ryanjameskennedy** [comment]
Now that we have uploaded prp to dockerhub, we can run the following to pull and convert the prp docker image to a singularity image:
```
singularity build bonsai-prp.sif docker://clinicalgenomicslund/bonsai-prp
```

**Comment by samuell** [comment]
Just a heads up that I'm working on this as part of the larger issue #260 right now.

(Sorry, had missed this issue).

I'm now primarily looking at creating minimal versions of some of the large databases to be able to run the self-test, so might not be too much overlap with what you have been discussed abovre regarding prp and tool containers.

**Comment by samuell** [comment]
The self test is now implemented as a GitHub Actions workflow, running the full self-test for S. Aureus, as per #265 . So, I guess this issue can be considered closed. Re-open if not!
