### ISSUE TITLE
Change to semantic versioning

### ISSUE THREAD

**Issue by LordRust** [genomic-medicine-sweden/JASEN#154]
The current versions are not proper v1 and v2 of the software and I absolutely think we should follow a semantic versioning of major.minor.patch. So a cleanup and rename of the current tags should be in order

**Comment by ryanjameskennedy** [comment]
Agreed. Existing releases should be changed from `1.0.0` and `2.0.0` to `0.1.0` and `0.2.0`. I think @sylvinite is the only one that can edit this...

**Comment by sylvinite** [comment]
Revised naming of current releases to to major.minor.build[-development stage].
As a 1.0 is yet to be released, backrolled previous releases to reflect this.
Do note that if 1.0 were out, last years continous development efforts would easily constitute at least one major update.
Added a CHANGELOG.md file. Please continously add a footnote in it when making a PR.
