### ISSUE TITLE
add serotyping of Ecoli as a module

### ISSUE THREAD

**Issue by LordRust** [genomic-medicine-sweden/jasen#155]
serotypefinder is a tool to mimic traditional serotyping in E. coli
The tool is a bit broken in the current state on bitbucket, so needs the following in order to use the committed settings. We could of course create a proper singularity recipe instead, but I tried this first.

# serotypefinder build
BuildDB
```
cd /builddir/somewhere/
git clone https://bitbucket.org/genomicepidemiology/serotypefinder_db.git
cd serotypefinder_db
export STFinder_DB=$(pwd)
python3 INSTALL.py kma_index
```
Build tool
```
cd /builddir/somewhere/
git clone --depth 1 --branch 2.0.2 https://bitbucket.org/genomicepidemiology/serotypefinder.git
cd serotypefinder
sed -i -e 's/FROM debian:stretch/FROM python:3.7-slim/' Dockerfile
sed -i -e 's/python3-pip/gcc make/' Dockerfile
sed -i -e 's/ENV DEBIAN_FRONTEND Teletype/# ENV DEBIAN_FRONTEND Teletype/' Dockerfile
sed -i -e 's:rm -rf /var/cache/apt/:# rm -rf /var/cache/apt/:' Dockerfile
sed -i -e 's/apt-get/apt/' Dockerfile
sed -i -e 's/    ; \\/    ;/' Dockerfile

docker build -t serotypefinder:2.0.2 .
sudo singularity build serotypefinder202.sif docker-daemon://serotypefinder:2.0.2
```
Execute and bid proper places as usual. Output folders must be created first
```
mkdir testdir
singularity exec --no-home --bind /data --bind /builddir serotypefinder202.sif serotypefinder.py -i /data/ecoli/sample.fasta -o testdir -p /builddir/serotypefinder_db/
```

**Comment by ryanjameskennedy** [comment]
Could we not just `wget` the [singularity image from galaxyproject](https://depot.galaxyproject.org/singularity/serotypefinder%3A2.0.1--py39hdfd78af_0)?

**Comment by ryanjameskennedy** [comment]
The problem is that we want to provide JASEN as a singularity pipeline but here we're using docker...

**Comment by ryanjameskennedy** [comment]
Serotypefinder is an singularity image in [galaxyproject](serotypefinder:2.0.1--py39hdfd78af_0)[serotypefinder:2.0.1--py39hdfd78af_0](https://depot.galaxyproject.org/singularity/serotypefinder%3A2.0.1--py39hdfd78af_0)
