### ISSUE TITLE
Write deployment script as Makefile

### ISSUE THREAD

**Issue by samuell** [genomic-medicine-sweden/JASEN#164]
## Background

I noticed that the deployment script (deploy_references_singularity.sh) will start over completely from scratch even if some of the references are already available, which is a bit troublesome since the script takes a really long time to run (at least an hour or two I think).

In particular if something happens during the installation, it is right now not possible to troubleshoot it and the restart the installation.

## Suggested solution

If writing the installation script as a Makefile with a few rules/steps that depend on each other, it would be possible to restart the script from partially finished installations, as well as only updating selected databases (e.g. by deleting them and rerunning the whole thing), without downloading everything from scratch.

(One caveat for Makefiles which I found useful when one needs to use more complex bash constructs, is to run stuff via bash, by including a `bash -c 'script-here'` line as part of the Make rule)

**Comment by samuell** [comment]
It might also perhaps make it easier to debug and solve issues like #163

**Comment by ryanjameskennedy** [comment]
By all means go ahead! Sounds great!

**Comment by samuell** [comment]
> By all means go ahead! Sounds great!

Sure, happy to take a stab at it!

**Comment by samuell** [comment]
I think it probably should wait for #156 though so as not to clash with changes there, right?

**Comment by ryanjameskennedy** [comment]
Is there no way to comment that out to just test if it works without it?
