### ISSUE TITLE
Add Klebsillia pneumonia prodigal training file

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#165]
Add the [prodigal trianing file](https://github.com/B-UMMI/chewBBACA/issues/21) for K. pneumonia. A [PR](https://github.com/mickaelsilva/prodigal_training_files/pull/2) has been created for this issue in the [prodigal training file repository](https://github.com/mickaelsilva/prodigal_training_files).

**Comment by ryanjameskennedy** [comment]
So this repository was no longer being maintained and thus my PR was closed. I have created a new [PR](https://github.com/B-UMMI/chewBBACA/pull/183) on chewBBACA's official repository.

**Comment by ryanjameskennedy** [comment]
Now comes the question, do we delete our current [prodigal_training_files submodule](https://github.com/mickaelsilva/prodigal_training_files/tree/3a2a33f3e3542f11ab270ac41e35fbd2ac1d49c8) and replace it with the [chewBBACA repository](https://github.com/B-UMMI/chewBBACA) that contains the official, maintained [prodigal_training_files](https://github.com/B-UMMI/chewBBACA/tree/master/CHEWBBACA/prodigal_training_files) s well as a lot of unwated code that equates to ~218Mb of space (pretty big imo). Alternatively, we copy all of their files into our prodigal_training_files directory and creat a git action to notify us when they update this part of their repository? @LordRust @sylvinite

**Comment by sylvinite** [comment]
Ideally we'd just submodule a subset of the chewbbaca repo. We discussed so ideas on how to do that.
If it doesn't work out, just copy the files, and make it **really really really** clear what commitid the database is on.
