### ISSUE TITLE
Mlst allele call with question mark bug

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#172]
Prp is not able to process the following:
```
[
   {
      "scheme" : "saureus",
      "sequence_type" : "-",
      "filename" : "saureus_test.fasta",
      "alleles" : {
         "gmk" : "5",
         "tpi" : "8",
         "arcC" : "7",
         "glpF" : "1",
         "aroE" : "1133?",
         "pta" : "8",
         "yqiL" : "6"
      },
      "id" : "saureus_test.fasta"
   }
]
```
This obviously due to `aroE` suggesting a `1133?` allele with a question mark included.

**Comment by LordRust** [comment]
Mmm, the question mark indicates that this is a novel allele with 1133 as the closest hit. Note that there is no ST assigned as well. These can initially keep the question mark if we like, but should be assigned a new allele and ST after submission to pubmlst.

You can also translate any allele with a ? to "novel" if you like, the information that the closest one is 1133 is not that valuable.

I do have a solution from Henning to the pubmlst submission via API coming up, so when we have that implemented the "novel" status should only be temporary for a week or so.
