### ISSUE TITLE
Fix mtuberculosis output

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#209]
The following changes need to be made:
- [x] Snippy result needs to be removed.
- [x] `ref_codon` & `alt_codon` -> `ref_nt` & `alt_nt`.
- [x] Add `nucleotide_change` & `protein_change`.
- [x] Add who confidence annotation.
- [x] Add tbprofiler drugs annotation.
- [x] Change tbprofiler `type`
- [x] Add `get_mutation_type` fuction for mykrobe to assess whether mutation = `substitution`/`insertion`/`deletion`

**Comment by ryanjameskennedy** [comment]
Mykrobe's mutation reporting style is not consistent. Sometimes its nucleotide other times its amino acids, e.g.

1. `gyrA_A90V-GCG7569GTG` -> A90V (amino acid change).
2. `ethA_GG847G-CC4326626C` -> GG847G (nucleotide deletion).

**Comment by LordRust** [comment]
If you just try to make a guess based on this, how do you differentiate between an amino acid change A90G (alanine-glycine) and nucleotide A90G (Adenine-Guanine)?
