### ISSUE TITLE
Add --calling_params '-q 15' to the tb-profiler profile command

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/jasen#257]
With the current way of doing the qc in tbprofiler, we would likely weed out quite a few false minority variants if we add `--calling_params '-q 15'` to the `tb-profiler profile` command. This would remove a lot of the noise. This is slightly hacky since it would only work well on Illumina data generated with the new Q value binning system they started with on the NovaSeq.

**Comment by mhkc** [comment]
Seems from your description that that `--calling_params '-q 15'` might be too specific for a general rule. I think this is something that instead could go into the documentation and should be up to the individual users to configure.
