### ISSUE TITLE
Create readthedocs for pipeline containing software used in pipeline

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/jasen#258]

**Comment by mhkc** [comment]
Good idea! We should start document how to setup and configure jasen.

**Comment by samuell** [comment]
Great idea! I might chip in that I've found MkDocs much easier to work with, as seem many others think too: https://www.mkdocs.org/ (E.g. we used it for [SciPipe](https://scipipe.org) with the popular Material for MkDocs theme).

ReadTheDocs, at least by default, wants content in the somewhat cryptic .rst format, while mkdocs is pure and simple Markdown.

**Comment by samuell** [comment]
> Do you know if we can automate the collection of SOUPs and SOUP versions?

What are SOUP versions? :thinking:
