### ISSUE TITLE
Getting "no loop devices available" when running Jasen test on wsl2 Ubuntu

### ISSUE THREAD

**Issue by hrydbeck** [genomic-medicine-sweden/jasen#294]
Command:
nextflow run main.nf -profile staphylococcus_aureus -config configs/nextflow.base.config --csv assets/test_data/samplelist.csv

Command error:
  FATAL:   container creation failed: mount /proc/self/fd/4->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/4: failed to find loop device: could not attach image file to loop device: no loop devices available

**Comment by mhkc** [comment]
This is not a Jasen error, here is a link to suggestions on how to fix this error: https://github.com/sylabs/singularity/issues/1499
