### ISSUE TITLE
Add profile for Streptococcus pyogenes

### ISSUE THREAD

**Issue by samuell** [genomic-medicine-sweden/jasen#304]
Add profile for basic analysis of Streptococcus pyogenes.

This is is of lower prio than the other organisms in #291, #302 & #303, but still something that has been asked for.

**Comment by ryanjameskennedy** [comment]
For Lund this is pretty high priority. We're interested in many _Streptococcus spp._ as well as EMM typing.

**Comment by ryanjameskennedy** [comment]
[Emmtyper](https://github.com/MDU-PHL/emmtyper) should be added using the [singularity image](emmtyper:0.2.0--py_0)[emmtyper:0.2.0--py_0](https://depot.galaxyproject.org/singularity/emmtyper%3A0.2.0--py_0).

**Comment by ryanjameskennedy** [comment]
@LordRust can you add the link to the cgmlst schema here please?

**Comment by LordRust** [comment]
Enterobase cgMLSTv1. Can be downloaded here: 
https://enterobase.warwick.ac.uk/species/streptococcus/download_data
