### ISSUE TITLE
Utilize dockerhub for deployment

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/JASEN#41]

**Comment by JD2112** [comment]
https://github.com/genomic-medicine-sweden/JASEN/issues/41  …
1. Dockefile and yml files added to the container.
2. .github/workflows added to the GHactions to automatically deploy the dockerhub image when there is a new push to "main" branch.
NOTE: needs to change for cron schedule or other setup.

**Comment by mhkc** [comment]
Is the idea that the pipeline shoud be run inside a docker container as default or is it just for testing?

Will all features work if run inside a docker container, like using singularity containers etc?
