### ISSUE TITLE
Nanopore track writeup

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/jasen#47]
Incorporate support for Nanopore sequence data.

**Comment by Emkago** [comment]
Here is Amaya's workflow for MRSA:

```shell
#!/usr/bin/bash
# This script performs denovo assembly and data polishing using the Flye and Medaka software tools.

# Enable Bash's pipefail and e options to exit immediately if any command fails.
set -eo pipefail

# Set up a trap for errors that prints an error message and exits the script.
trap 'exit_status="$?" && echo Failed on line: $LINENO at command: $BASH_COMMAND && echo "exit status $exit_status" && exit' ERR

# Check that the script was called with 4 arguments.
if [ $# -ne 4 ]
then
 echo "Usage: $0 <raw_reads_path> <flye_out_dir> <medaka_out_dir> <medaka_out_dir2>"
 echo "Please provide the path to the raw reads, the name of the Flye output directory, the name of the Medaka output directory, and the name of the Medaka output directory for the second round."
 exit 1
fi

# Assign the command-line arguments to variables.
reads="$1"
flye_out="$2"
medaka_out="$3"
medaka_out2="$4"

# Activate the Conda environment containing Flye.
source activate flye

# Run Flye with the specified parameters.
echo "Starting Flye..."
flye --nano-hq "$reads" -g 2.8m -o "$flye_out" -t 40 --asm-coverage 50

# Deactivate the Conda environment containing Flye.
conda deactivate

# Activate the Conda environment containing Medaka.
source activate medaka17

# Run Medaka with the specified parameters, using the Flye assembly as input.
echo "Starting Medaka round 1..."
medaka_consensus -i "$reads" -d "${flye_out}/assembly.fasta" -o "$medaka_out" -t 40 -m r941_min_high_g303

# Run Medaka again with the specified parameters, using the output of the first Medaka run as input.
echo "Starting Medaka round 2..."
medaka_consensus -i "$reads" -d "${medaka_out}/consensus.fasta" -o "$medaka_out2" -t 40 -m r941_min_high_g303

# Deactivate the Conda environment containing Medaka.
conda deactivate
```

**Comment by ryanjameskennedy** [comment]
That's great! So here's a checklist of what needs to be done:
[ ] Add the singularity images for [flye](https://depot.galaxyproject.org/singularity/flye:2.9.2--py39hd65a603_2) and [medaka](https://depot.galaxyproject.org/singularity/medaka:1.8.0--py39h771796b_0) to the [container/build_container.sh script](https://github.com/genomic-medicine-sweden/JASEN/blob/master/container/build_container.sh).
[ ] Add flye and medaka as a module in [nexflow-modules/modules](https://github.com/genomic-medicine-sweden/JASEN/tree/master/nextflow-modules/modules) using [skesa](https://github.com/genomic-medicine-sweden/JASEN/blob/master/nextflow-modules/modules/skesa/main.nf) or [spades](https://github.com/genomic-medicine-sweden/JASEN/blob/master/nextflow-modules/modules/spades/main.nf) as a guide. NB: Pay attention to the `when` command.
[ ] Import and call the respective modules in [workflows/bacterial_base.nf](https://github.com/genomic-medicine-sweden/JASEN/blob/master/workflows/bacterial_base.nf) und the assembly section and mix their output in the [assembly channel](https://github.com/genomic-medicine-sweden/JASEN/blob/dcb3edae2b402ab762a225ac8839136ec2e91760/workflows/bacterial_base.nf#L41).

A good start would be to try copy and paste existing code, create a PR, and I'll comment on what needs to be changed.
