### ISSUE TITLE
Validate pipeline results using MRSA data

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/JASEN#50]

**Comment by ryanjameskennedy** [comment]
I have done this in parallel with 10 validation samples. Worked perfectly after bug fixes that I have merged to the master branches of [JASEN](https://github.com/genomic-medicine-sweden/JASEN) and [nextflow-modules](https://github.com/genomic-medicine-sweden/nextflow-modules/tree/master). I will test E. coli next!

**Comment by ryanjameskennedy** [comment]
The pipeline has been tested using single-end (SE) and paired-end (PE) Illumina reads for MRSA, and SE Ion Torrent reads for MRSA and SE and PE Illumina reads for Ecoli. All worked as expected. I will close this issue.
