### ISSUE TITLE
Rename variable "cgmlstSchema" to better reflects its purpose

### ISSUE THREAD

**Issue by mhkc** [genomic-medicine-sweden/JASEN#56]
The variable `cgmlstSchema` found in the config is used to estimate the depth and breadth of sequencing coverage by defining a set of "core" regions in the reference genome.

**Comment by ryanjameskennedy** [comment]
Perhaps renaming the variable to `cgRegions` (core genome regions) might be better suited seeing as it's just a bed file @mhkc @LordRust?
