### ISSUE TITLE
Repository security with reviewing PR and unit testing

### ISSUE THREAD

**Issue by ryanjameskennedy** [genomic-medicine-sweden/JASEN#69]
Despite being bureaucratic and slower, I think it woud be a good to implement reviewer approval rules i.e. at least one person must approve a PR before merging to the main branch. Also, utilising git actions to perform tests (linting and unit tests similar to that of nf-core would be elegant).

**Comment by sylvinite** [comment]
Reverted repo to read access per default. Elevated those with a history of merging PRs (Currently RJK and IS) to that level of authority. Broke out the unit tests into the seperate issue https://github.com/genomic-medicine-sweden/JASEN/issues/99
Regarding CI looking for input. Travis was commonplace in the past but has been deemed insecure. Looking for input on the matter.
