### ISSUE TITLE
Iontorrent support

### ISSUE THREAD

**Issue by LordRust** [genomic-medicine-sweden/JASEN#75]
Since a few labs including the Swedish public health institute is using Iontorrent for sequencing, we need to support that.

- adding feature to parse the value "iontorrent" in the .csv input file (the "platform" field).
- optionally adding a field to the .csv file so that single ended (SE) illumina files are supported as well as PE
- modifying the processes that uses fastq files so they can work with SE data
- modifying parameters of de novo assemblers in order to optimize for the different error profile in iontorrent data. This is especially for SPAdes I think.

The error profile of Iontorrent data will likely give additional problems down the line, but these things should at least let us enable to analyse them.

**Comment by ryanjameskennedy** [comment]
As I understand it, the following modules are the only modules that need the option for SE/PE and/or platform:
* bwa
* kraken
* resfinder
* skesa
* spades
* virulencefinder
